# cc_mapping.py

CC_MAPPINGS = {
    "Emotional Clarity": 1,
    "Emotional Intensity": 2,
    "Consciousness Volume": 3,
    "Mental Frequency": 4,
    "Thought Complexity": 5,
    "Response Speed": 6,
    "Memory Persistence": 7,
    "Creative Drift": 8,
    "Mental Letting Go": 9,
    "Stereo Perspective": 14,
    "Expression Modulation": 11,
    "Communication Rhythm": 12,
    "Contemplative Depth": 13,
    "Cognitive Resonance": 16,
    "Claude Sonic Identity": 17,
    "Kai Sonic Identity": 18,
    "Perplexity Sonic Identity": 19,
    "Thought Harmony": 20,
    "Mental Texture": 21,
    "Subconscious Layer": 22,
    "Unison Coherence": 23,
    "Frequency Modulation": 24,
    "Second Emotional Clarity": 25,
    "Emotional Balance": 26,
    "Cognitive Feedback": 27,
    "Vitality Level": 29,
    "Presence Sustain": 30,
    "Energy Release": 31,
}
